name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python environment
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.9.19"

      - name: Cache dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Lint with Ruff
        run: |
          pip install ruff==0.8.0
          ruff check . --output-format=github

      - name: Lint with Mypy
        run: |
          pip install mypy==1.13.0
          mypy . --config-file pyproject.toml --ignore-missing-imports --no-namespace-packages
